# Generated by Django 4.0.4 on 2022-07-26 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweetid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweetid', models.JSONField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tweetkeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.JSONField(null=True)),
            ],
        ),
    ]
