# Generated by Django 4.0.4 on 2022-07-22 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tweetinput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Title', max_length=255)),
                ('tweetid', models.JSONField()),
                ('keyword', models.JSONField()),
            ],
        ),
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
