# Generated by Django 4.0.4 on 2022-07-28 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(default=' ', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='pub_date',
            field=models.DateTimeField(default=' '),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(default=' ', max_length=255),
        ),
    ]
