# Generated by Django 4.0.4 on 2022-07-22 18:33

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='body2',
            field=ckeditor.fields.RichTextField(default=' '),
        ),
    ]
