# Generated by Django 4.0.4 on 2022-07-22 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Climatedf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Title', max_length=255)),
                ('df', models.FileField(upload_to='', verbose_name='uploads/%Y/%m/%d/')),
            ],
        ),
    ]
