# Generated by Django 4.0.4 on 2022-07-28 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fooddata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='climatedf',
            name='df',
            field=models.FileField(default=' ', upload_to='', verbose_name='uploads/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='foodinput',
            name='cat_items_dict',
            field=models.JSONField(default=' '),
        ),
    ]
