# Generated by Django 4.0.4 on 2022-07-26 08:52

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Title', max_length=255)),
                ('pub_date', models.DateTimeField(null=True)),
                ('sum', models.TextField(default=' ', max_length=255)),
                ('image', models.ImageField(upload_to='images/')),
                ('body', ckeditor.fields.RichTextField(default=' ')),
            ],
        ),
        migrations.CreateModel(
            name='MyCv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Title', max_length=255)),
                ('my_cv', models.FileField(upload_to='images/')),
            ],
        ),
    ]
