# Generated by Django 4.0.4 on 2022-07-16 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutme', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyCv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Title', max_length=255)),
                ('my_cv', models.FileField(upload_to='images/')),
            ],
        ),
    ]
