# Generated by Django 4.0.4 on 2022-07-05 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aboutme', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutme',
            name='file',
        ),
        migrations.RemoveField(
            model_name='aboutme',
            name='summary',
        ),
    ]
