# Generated by Django 4.0.4 on 2022-07-05 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aboutme', '0002_remove_aboutme_image_remove_aboutme_summary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutme',
            name='file',
        ),
    ]
