# Generated by Django 4.0.4 on 2022-07-28 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='climate',
            name='image',
            field=models.ImageField(default=' ', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='climate',
            name='pub_date',
            field=models.DateTimeField(default=' ', null=True),
        ),
        migrations.AlterField(
            model_name='google',
            name='image',
            field=models.ImageField(default=' ', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='google',
            name='pub_date',
            field=models.DateTimeField(default=' ', null=True),
        ),
        migrations.AlterField(
            model_name='health',
            name='image',
            field=models.ImageField(default=' ', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='health',
            name='pub_date',
            field=models.DateTimeField(default=' ', null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='image',
            field=models.ImageField(default=' ', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='job',
            name='pub_date',
            field=models.DateTimeField(default=' ', null=True),
        ),
        migrations.AlterField(
            model_name='ontology',
            name='image',
            field=models.ImageField(default=' ', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='ontology',
            name='pub_date',
            field=models.DateTimeField(default=' ', null=True),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='image',
            field=models.ImageField(default=' ', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='pub_date',
            field=models.DateTimeField(default=' ', null=True),
        ),
    ]
