# Generated by Django 4.0.4 on 2022-07-22 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Climate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Title', max_length=255)),
                ('pub_date', models.DateTimeField(null=True)),
                ('image', models.ImageField(upload_to='images/')),
                ('body', models.TextField(default=' ')),
            ],
        ),
        migrations.CreateModel(
            name='Google',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Title', max_length=255)),
                ('pub_date', models.DateTimeField(null=True)),
                ('image', models.ImageField(upload_to='images/')),
                ('body', models.TextField(default=' ')),
            ],
        ),
        migrations.CreateModel(
            name='Health',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Title', max_length=255)),
                ('pub_date', models.DateTimeField(null=True)),
                ('image', models.ImageField(upload_to='images/')),
                ('body', models.TextField(default=' ')),
            ],
        ),
        migrations.CreateModel(
            name='Ontology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Title', max_length=255)),
                ('pub_date', models.DateTimeField(null=True)),
                ('image', models.ImageField(upload_to='images/')),
                ('body', models.TextField(default=' ')),
            ],
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Title', max_length=255)),
                ('pub_date', models.DateTimeField(null=True)),
                ('image', models.ImageField(upload_to='images/')),
                ('body', models.TextField(default=' ')),
            ],
        ),
    ]
