# Generated by Django 4.0.4 on 2022-07-22 16:13

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_climate_google_health_ontology_tweet'),
    ]

    operations = [
        migrations.AddField(
            model_name='google',
            name='body2',
            field=ckeditor.fields.RichTextField(default=' '),
        ),
    ]
