# Generated by Django 4.0.4 on 2022-07-22 16:21

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_google_body2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='google',
            name='body2',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
