# Generated by Django 4.0.4 on 2022-07-22 17:16

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_alter_google_body2'),
    ]

    operations = [
        migrations.AddField(
            model_name='climate',
            name='body2',
            field=ckeditor.fields.RichTextField(default=' '),
        ),
        migrations.AlterField(
            model_name='google',
            name='body2',
            field=ckeditor.fields.RichTextField(default=' '),
        ),
        migrations.AlterField(
            model_name='google',
            name='image',
            field=models.ImageField(height_field=128, upload_to='images/', width_field=128),
        ),
    ]
