# Generated by Django 4.0.4 on 2022-07-22 18:33

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_climate_body2_alter_google_body2_alter_google_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='health',
            name='body2',
            field=ckeditor.fields.RichTextField(default=' '),
        ),
        migrations.AddField(
            model_name='job',
            name='body2',
            field=ckeditor.fields.RichTextField(default=' '),
        ),
        migrations.AddField(
            model_name='ontology',
            name='body2',
            field=ckeditor.fields.RichTextField(default=' '),
        ),
        migrations.AddField(
            model_name='tweet',
            name='body2',
            field=ckeditor.fields.RichTextField(default=' '),
        ),
    ]
