# Generated by Django 4.0.4 on 2022-07-22 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_health_body2_job_body2_ontology_body2_tweet_body2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='google',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
